In [ ]:
import pandas as pd
data=pd.read_excel('loan3(na).xlsx')

In [ ]:
data.head()

   loan  Industry_type  Company_type  ...  Age  Education  Credit
0   1.0              1           1.0  ...    3          2       2
1   1.0              2           1.0  ...    4          3       2
2   1.0              1           1.0  ...    3          4       1
3   1.0              2           1.0  ...    3          4       2
4   1.0              1           1.0  ...    2          3       2

[5 rows x 10 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   loan               205 non-null    float64
 1   Industry_type      206 non-null    int64
 2   Company_type       205 non-null    float64
 3   Beginning_time     206 non-null    int64
 4   Collateral         206 non-null    int64
 5   Bank_relationship  206 non-null    int64
 6   Capital_increase   206 non-null    int64
 7   Age                206 non-null    int64
 8   Education          206 non-null    int64
 9   Credit             206 non-null    int64
dtypes: float64(2), int64(8)
memory usage: 16.2 KB

In [ ]:
df1=data.dropna()
X=df1[['Industry_type','Company_type','Beginning_time','Bank_relationship','Capital_increase','Age','Education','Credit']]
y=df1['loan'] 
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=5,stratify=df1['loan'])

# **分類器**

In [ ]:
#solver='lbfgs'：利用牛頓法求解，默認為梯度下降法；hidden_layer_sizes=(5,3)表示隱藏層有兩層第一層為八個神經元，第二層為三個神經元
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(8,3), random_state=1)
clf.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(8, 3), random_state=1, solver='lbfgs')

In [ ]:
clf_pred= clf.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,clf_pred))

              precision    recall  f1-score   support

         1.0       0.84      1.00      0.92        38
         2.0       1.00      0.46      0.63        13

    accuracy                           0.86        51
   macro avg       0.92      0.73      0.77        51
weighted avg       0.88      0.86      0.84        51

In [ ]:
#計算混淆矩陣(confusion matrix)
print(confusion_matrix(y_test,clf_pred))

[[38  0]
 [ 7  6]]

# **數量預測：迴歸器**

In [ ]:
import pandas as pd
data2=pd.read_excel('boston_house.xlsx')

In [ ]:
data2.head()

   Unnamed: 0     CRIM    ZN  INDUS  CHAS  ...  TAX  PTRATIO       B  LSTAT  PRICE
0           0  0.00632  18.0   2.31     0  ...  296     15.3  396.90   4.98   24.0
1           1  0.02731   0.0   7.07     0  ...  242     17.8  396.90   9.14   21.6
2           2  0.02729   0.0   7.07     0  ...  242     17.8  392.83   4.03   34.7
3           3  0.03237   0.0   2.18     0  ...  222     18.7  394.63   2.94   33.4
4           4  0.06905   0.0   2.18     0  ...  222     18.7  396.90   5.33   36.2

[5 rows x 15 columns]

In [ ]:
X=data2[['CRIM','INDUS','NOX','DIS','AGE','RAD','TAX','ZN','RM','PTRATIO','B','LSTAT']]
y=data2['PRICE'] 
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=5)

In [ ]:
#hidden_layer_sizes=(5,3)表示隱藏層有一層第一層為十二個神經元，設定激活函數為relu，默認即為relu,max_iter:迭代次數，默認：200
from sklearn.neural_network import MLPRegressor
reg = MLPRegressor(random_state=1, hidden_layer_sizes=(12), activation='relu',max_iter=10000)
reg.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=12, max_iter=10000, random_state=1)

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
# 使用X_test預測y，得到y_pred1 
y_pred1 = reg.predict(X_test)
rmse = sqrt(mean_squared_error(y_test, y_pred1)) 
print("rms: %.3f" % rmse)

rms: 4.521

In [ ]:
data2['PRICE'].mean()

22.532806324110698

# **練習題**
(1)請利用boston_house(type).xlsx檔案中的指標，以類神經網路來預測boston house的房價高低(Price Type)，並說明分析結果。

(2)請利用boston_house(type).xlsx檔案中的指標，以類神經網路來預測boston house的房價(Price)，並說明分析結果。

註： 1.資料與預測指標說明如附檔。 2.Price Type:1表單位房價低於20，2表單位房價高於20。