In [ ]:
import pandas as pd
df=pd.read_excel('Exercise1(RA).xlsx')

In [ ]:
df.head()

   education_years  working_years  salary
0                6              7      38
1               12             14      53
2                9              5      40
3               16              8      50
4               18              6      55

# 一、線性迴歸模式：解釋分析模式
用於分析哪些自變數(因素)會影響到某個依變數之統計分析模式，其中依變數需為“屬量”的變數，自變數亦為屬量變數

    可參考https://www.statsmodels.org/stable/api.html

In [ ]:
X = df[["education_years","working_years"]] #education_years, working_years為自變數,可自行調整
y = df['salary']

In [ ]:
import statsmodels.api as smf
RA = smf.OLS(y,X).fit()
print(RA.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                 salary   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.986
Method:                 Least Squares   F-statistic:                              783.9
Date:                Tue, 25 May 2021   Prob (F-statistic):                    1.01e-19
Time:                        08:37:17   Log-Likelihood:                         -67.496
No. Observations:                  22   AIC:                                      139.0
Df Residuals:                      20   BIC:                                      141.2
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
education_years     2.4237      0.190     12.725      0.000       2.026       2.821
working_years       2.2290      0.249      8.968      0.000       1.711       2.747
==============================================================================
Omnibus:                        2.759   Durbin-Watson:                   2.691
Prob(Omnibus):                  0.252   Jarque-Bera (JB):                1.217
Skew:                           0.015   Prob(JB):                        0.544
Kurtosis:                       1.848   Cond. No.                         3.65
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
#進行迴歸分析，跑出迴歸分析解釋分析表(從statsmodels.formula.api 匯入ols線性迴歸分析)
#PTS為依變數；A, OEFF,TO為自變數，進行迴歸分析
import statsmodels.formula.api as smf
RA = smf.ols("salary ~ education_years+ working_years", df).fit()
print(RA.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.905
Method:                 Least Squares   F-statistic:                     101.6
Date:                Tue, 25 May 2021   Prob (F-statistic):           7.16e-11
Time:                        05:56:09   Log-Likelihood:                -42.477
No. Observations:                  22   AIC:                             90.95
Df Residuals:                      19   BIC:                             94.23
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          23.6193      1.835     12.874      0.000      19.779      27.459
education_years     1.4155      0.100     14.112      0.000       1.206       1.625
working_years       0.8374      0.136      6.178      0.000       0.554       1.121
==============================================================================
Omnibus:                        4.134   Durbin-Watson:                   2.202
Prob(Omnibus):                  0.127   Jarque-Bera (JB):                3.409
Skew:                          -0.947   Prob(JB):                        0.182
Kurtosis:                       2.637   Cond. No.                         67.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
df.head()

   education_years  working_years  salary
0                6              7      38
1               12             14      53
2                9              5      40
3               16              8      50
4               18              6      55

# 二、線性迴歸模式：預測分析模式_機器學習
利用線性迴歸模型，建立依變數之預測模型

In [ ]:
#2.用線性回歸做訓練線性模型:
#import基本函式庫
import pandas as pd
import numpy as np

#準備X & y array
X = df[["education_years","working_years"]] #education_years, working_years為自變數,可自行調整
y = df['salary']            #salary為依變數,可自行調整

#將資料分成訓練組及測試組
from sklearn.model_selection import train_test_split

#test_size代表測試組比例。random_state代表設定隨機種子，讓測試結果可被重複
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=333)

#載入線性迴歸，並訓練模型
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

#取得截距。如果公式是y=a+bx，a即是截距
print(lm.intercept_)
print(lm.coef_)

23.707838579005255
[1.39831842 0.87093002]

In [ ]:
#取得迴歸係數，並用Data Frame顯示:pd.DataFrame(資料,列的名稱,行的名稱)
#lm.coef_
#X_train.columns
cdf = pd.DataFrame(lm.coef_,X_train.columns,columns=['Coef'])
cdf

                     Coef
education_years  1.398318
working_years    0.870930

計算模式績效:RMSE, R_Square

In [ ]:
#計算RMSE (可改用from sklearn.metrics import mean_squared_error, r2_score)
MSE1= np.mean((y_train - lm.predict(X_train) )** 2)
RMSE1=MSE1**0.5
MSE2= np.mean((y_test - lm.predict(X_test) )** 2)
RMSE2=MSE2**0.5
print('train_RMSE=%.3f,test_RMSE=%.3f'%(RMSE1,RMSE2))

train_RMSE=1.774,test_RMSE=1.472

In [ ]:
#計算R_Square,
R2_train = lm.score(X_train,y_train)
R2_test = lm.score(X_test,y_test)

print('train_R2=%.3f, test_R2=%.3f'%(R2_train,R2_test))

train_R2=0.870, test_R2=0.768

In [ ]:
df['salary'].mean()

46.0

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
# 使用X_test預測y，得到y_pred1 
y_pred1 = lm.predict(X_test)
rms = sqrt(mean_squared_error(y_test, y_pred1)) 
print("rms: %.3f" % rms)

rms: 1.472

In [ ]:
#輸入X1,X2, 計算模式所得的y值
lm.predict([[12,15],[8,10]])

array([53.55160989, 43.60368612])

In [ ]:
#以陣列表示待預測之自變數
X_1=pd.DataFrame([[12,15],[8,10]])
print(X_1)

    0   1
0  12  15
1   8  10

In [ ]:
#計算出上述陣列中自變數之預測值(y)
list(lm.predict(X_1))

[53.55160989462255, 43.60368612275012]

# 練習題：請以nba2.xlsx之資料，以1Q, 2Q, 3Q建立PTS之線性迴歸模式，並說明你預測模型的準確度。

In [ ]:
import pandas as pd
df=pd.read_excel('nba2.xlsx')

In [ ]:
df.head()

                    DATASET  R/P        DATE  ... REST DAYS  OPENING ODDS  SPREAD
0  2016-2017 Regular Season    1  10/25/2016  ...         3         205.5     9.5
1  2016-2017 Regular Season    1  10/25/2016  ...         3          -9.5    -9.5
2  2016-2017 Regular Season    1  10/25/2016  ...         3         194.0     6.0
3  2016-2017 Regular Season    1  10/25/2016  ...         3          -6.0    -6.0
4  2016-2017 Regular Season    1  10/25/2016  ...         3         210.5     8.0

[5 rows x 43 columns]

In [ ]:
df1=df.rename(columns={'1Q':'Q1','2Q':'Q2','3Q':'Q3','4Q':'Q4'})

In [ ]:
import statsmodels.formula.api as smf
RA = smf.ols('PTS ~ Q1+Q2+Q3', df1).fit()
print(RA.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    PTS   R-squared:                       0.709
Model:                            OLS   Adj. R-squared:                  0.709
Method:                 Least Squares   F-statistic:                     1997.
Date:                Tue, 25 May 2021   Prob (F-statistic):               0.00
Time:                        08:19:21   Log-Likelihood:                -8114.0
No. Observations:                2460   AIC:                         1.624e+04
Df Residuals:                    2456   BIC:                         1.626e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     27.2656      1.021     26.697      0.000      25.263      29.268
Q1             0.9981      0.023     44.021      0.000       0.954       1.043
Q2             0.9868      0.023     43.095      0.000       0.942       1.032
Q3             0.9848      0.022     43.863      0.000       0.941       1.029
==============================================================================
Omnibus:                      168.098   Durbin-Watson:                   1.637
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              286.526
Skew:                           0.513   Prob(JB):                     6.05e-63
Kurtosis:                       4.319   Cond. No.                         356.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.