In [ ]:
import pandas as pd
df=pd.read_excel('loan4.xlsx')

In [ ]:
df.head()

   loan  Industry_type  Company_type  ...  Age  Education  Credit
0     1              1             1  ...    3          2       2
1     1              2             1  ...    4          3       2
2     1              1             1  ...    3          4       1
3     1              2             1  ...    3          4       2
4     1              1             1  ...    2          3       2

[5 rows x 10 columns]

In [ ]:
#將含有缺失值的列（特徵向量）去掉; 決定特徵變數(X)與目標變數(Y)
df1=df.dropna()
X=df1[['Industry_type','Company_type','Beginning_time','Bank_relationship','Capital_increase','Age','Education','Credit']]
y=df1['loan']

In [ ]:
#將資料切割成訓練集(train)及測試集(test)，決定切割比例test_size=0.25，隨機抽取第一筆資料的起始值random_state=5
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=5)

In [ ]:
#利用邏輯斯迴歸分析建立預測模式
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#計算正確率、精準度、召回率及綜合指標f1(train訓練集)
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_train)
print(confusion_matrix(y_train,LR_pred))
print("======================================================\n")
print(classification_report(y_train,LR_pred))

[[ 25  15]
 [  4 110]]
======================================================

              precision    recall  f1-score   support

           0       0.86      0.62      0.72        40
           1       0.88      0.96      0.92       114

    accuracy                           0.88       154
   macro avg       0.87      0.79      0.82       154
weighted avg       0.88      0.88      0.87       154

In [ ]:
#計算正確率、精準度、召回率及綜合指標f1(test測試集)
from sklearn.metrics import classification_report,confusion_matrix
LR_pred= LR.predict(X_test)
print(confusion_matrix(y_test,LR_pred))
print("======================================================\n")
print(classification_report(y_test,LR_pred))

[[ 9  3]
 [ 3 37]]
======================================================

              precision    recall  f1-score   support

           0       0.75      0.75      0.75        12
           1       0.93      0.93      0.93        40

    accuracy                           0.88        52
   macro avg       0.84      0.84      0.84        52
weighted avg       0.88      0.88      0.88        52

# 切割值
利用切割值p_value決定目標變數的類別

In [ ]:
#從LR預測模型中取得Y=0及Y=1的預測機率值(pre_test_prob)
pre_test_prob=pd.DataFrame(LR.predict_proba(X_test))
pre_test_prob

           0         1
0   0.146245  0.853755
1   0.060292  0.939708
2   0.508988  0.491012
3   0.101020  0.898980
4   0.037411  0.962589
5   0.919489  0.080511
6   0.486783  0.513217
7   0.130632  0.869368
8   0.082001  0.917999
9   0.651158  0.348842
10  0.123856  0.876144
11  0.117443  0.882557
12  0.038425  0.961575
13  0.117443  0.882557
14  0.062484  0.937516
15  0.954166  0.045834
16  0.274005  0.725995
17  0.966314  0.033686
18  0.072791  0.927209
19  0.701487  0.298513
20  0.020657  0.979343
21  0.804526  0.195474
22  0.246804  0.753196
23  0.050314  0.949686
24  0.122811  0.877189
25  0.101020  0.898980
26  0.123856  0.876144
27  0.330419  0.669581
28  0.812390  0.187610
29  0.390294  0.609706
30  0.947573  0.052427
31  0.117443  0.882557
32  0.925237  0.074763
33  0.140025  0.859975
34  0.034342  0.965658
35  0.071293  0.928707
36  0.104706  0.895294
37  0.088937  0.911063
38  0.081828  0.918172
39  0.436691  0.563309
40  0.040412  0.959588
41  0.075401  0.924599
42  0.062484  0.937516
43  0.781451  0.218549
44  0.963220  0.036780
45  0.140089  0.859911
46  0.109373  0.890627
47  0.119543  0.880457
48  0.039241  0.960759
49  0.117443  0.882557
50  0.235740  0.764260
51  0.071293  0.928707

In [ ]:
#以切割值調整精準度,p為切割值，取得預測結果
p=0.2
pre_test=pre_test_prob[0].apply(lambda x: 0 if x>p else 1)
pre_test

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     1
9     0
10    1
11    1
12    1
13    1
14    1
15    0
16    0
17    0
18    1
19    0
20    1
21    0
22    0
23    1
24    1
25    1
26    1
27    0
28    0
29    0
30    0
31    1
32    0
33    1
34    1
35    1
36    1
37    1
38    1
39    0
40    1
41    1
42    1
43    0
44    0
45    1
46    1
47    1
48    1
49    1
50    0
51    1
Name: 0, dtype: int64

In [ ]:
#計算混淆矩陣
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pre_test))

[[10  2]
 [ 9 31]]

In [ ]:
#評估預測結果的精準度、召回率、F1
from sklearn import metrics
print(metrics.classification_report(y_test,pre_test))

              precision    recall  f1-score   support

           0       0.53      0.83      0.65        12
           1       0.94      0.78      0.85        40

    accuracy                           0.79        52
   macro avg       0.73      0.80      0.75        52
weighted avg       0.84      0.79      0.80        52

# **＃以統計分析表格呈現邏輯斯迴歸分析結果**

In [ ]:
#載入統計分析模型套件，定義自變數與依變數
import statsmodels.api as sm 
import pandas as pd  

# defining the dependent and independent variables 
Xtrain = df[['Industry_type','Company_type','Beginning_time','Bank_relationship','Capital_increase','Age','Education','Credit']] 
ytrain = df[['loan']] 

# building the model and fitting the data

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
#建立fitting data的邏輯斯迴歸模型
log_reg = sm.Logit(ytrain, Xtrain).fit()

Optimization terminated successfully.
         Current function value: 0.322091
         Iterations 7

In [ ]:
#列出分析表格
print(log_reg.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                   loan   No. Observations:                  206
Model:                          Logit   Df Residuals:                      198
Method:                           MLE   Df Model:                            7
Date:                Mon, 18 Oct 2021   Pseudo R-squ.:                  0.4299
Time:                        08:15:16   Log-Likelihood:                -66.351
converged:                       True   LL-Null:                       -116.39
Covariance Type:            nonrobust   LLR p-value:                 1.042e-18
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Industry_type        -1.2614      0.507     -2.488      0.013      -2.255      -0.268
Company_type          0.3423      0.563      0.608      0.543      -0.762       1.446
Beginning_time        0.1126      0.312      0.361      0.718      -0.498       0.724
Bank_relationship    -1.6125      0.479     -3.368      0.001      -2.551      -0.674
Capital_increase     -0.4715      0.399     -1.182      0.237      -1.253       0.310
Age                   0.6551      0.363      1.805      0.071      -0.056       1.366
Education            -0.2228      0.303     -0.735      0.462      -0.817       0.371
Credit                2.9966      0.599      5.006      0.000       1.823       4.170
=====================================================================================

# 練習：
1.請以salary.xlsx檔案資料的工作年資、教育年資與性別等特徵建立預測模式，預測年所得高於50或低於50（萬元）。

2.比較說明工作年資、教育年資與性別對年所得的影響。

# 作業：
(1)請利用boston_house(type).xlsx檔案中的指標來預測boston house的房價高低(Price Type)，分析後請說明預測分析之結果。
(2)請分析說明影響房價高低的主要特徵(變數)。
(3)請調整切割值p，使得辨識為高房價的資料Precision值可達0.9。。

註： 1.資料與預測指標說明如附檔。 2.Price Type:1表單位房價低於20，2表單位房價高於20。